name: PR Labeler
on:
  - pull_request_target

jobs:
  triage:
    runs-on: ubuntu-24.04
    permissions: write-all
    steps:
      - name: Check skip conditions
        run: |
          if [[ "${{ github.repository }}" != "azerothcore/azerothcore-wotlk" ]]; then
            echo "::notice ::Job skipped: Not the main repository (found ${{ github.repository }})"
            exit 78
          fi
          if [[ "${{ github.event.pull_request.draft }}" == "true" ]]; then
            echo "::notice ::Job skipped: PR is a draft"
            exit 78
          fi
      - name: Real labeler step
        if: github.repository == 'azerothcore/azerothcore-wotlk' && !github.event.pull_request.draft
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
          sync-labels: true
